name: Despliegue Automático

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Compilar Proyecto
        run: |
          npm install
          npx ng build

      - name: Subir al servidor IONOS
        uses: appleboy/scp-action@master
        with:
          host: 213.165.70.214
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/repaso-despligue/browser/*"
          target: "/var/www/repaso-despligue"
          strip_components: 3